- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/persistence/repository/MigrationHistory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/resources/MigrationHistoryResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/MigrationHistoryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/visits/VisitsMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/persistence/repository/MigrationHistoryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationServiceTest.kt
This PR will create the migration history record and update it when migration job has finished 
- Also added basic endpoints to read all migration records
- Delete all records
Still to be done
- Record number of records migrated
- Record number of records failed
- Better GET endpoint with filtering
> SDI-104 Add basic call to add and update migration history

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/MigrationQueueService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitMappingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/visits/VisitsMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitMappingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/VisitMappingApiMockServer.kt
- Reads DLQ to record number of failures
- Read visit migration table to read number of successes
The DLQ is not 100% reliable since there could DLQ messages on queue already, but will mention this in Run Book when done
> SDI-104 Add counts to history record

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/resources/MigrationHistoryResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitMigrationResource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/history/MigrationHistoryIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/visits/VisitsMigrationIntTest.kt
- Generic `history` endpoint now protected by admin role
- Visits specific version of endpoint 
This is required for 2 reasons:
- Visit migration users should only see visit migrations
- Has ability to understand the filter, so can easily and reliable filter by prison
> SDI-104 Add Visits specific history endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/MigrationSentencingMessageListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMappingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMessages.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/sentencing/SentencingMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
So foundation change to migrate both types at same time.
Where we referred to "sentence adjustments"  and that is now used to reference the 2 types of adjustments we now use the language "sentencing adjustments"; this includes "sentence adjustments" and "key date adjustments"
> SDI-538 Mapping is now sentence/key date agnostic.

- helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesPrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/listeners/ListenerHelpers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingPrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsPrisonOffenderEventListener.kt
- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesPrisonOffenderEventListenerTest.kt
* Add sentencing prisoner NO-OP events listener 
* Added duplicate visits listener ready for migration to own queue
* Added duplicate incentives listener ready for migration to own queue
Path to Live
* Cloud Platform changes go live for new queues that do not subscribe to anything 
* This code version goes live
* Cloud Platform second change to switch subscription to own queues
* Remove all listener from this code
> SDI-554 sentence adjustment create

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
To prevent infinite synchronisation in the 2-way sync, both services checks what service made the change and suppress forwarding create/updates/deletes.
The exception is for DELETEs since there is no way of knowing if NOMIS or DPS initiated the delete (since the audit column is not updated).
So this change assumes the DELETE in the sentencing service and mapping are idempotent and will no error if a DELETE is called on an already deleted element.
> SDI-702 Always try to delete adjustment even when last update came from DPS

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/WebClientHelpers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/SentencingApiMockServer.kt
This allows this theoretical edge case to work:
* Adjustment created in DPS
* Adjustment delete in DPS
* Update service deletes NOMIS record 
* Triggers messages this service so this service also attempts to delete adjustment that has already been deleted
* Update service deletes Mapping
* Call to DPS service returns 404 since adjustment is already deleted
So treat DELETE in DPS as idempotent
> SDI-702 Allow DPS delete to return 404 without error

- openapi-specs/nomis-mapping-service-api-docs.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMappingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationMessageListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/history/MigrationMapping.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/AdjudicationsApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
This uses new endpoint that will eventually  create all mappings (hearings etc) in one go.
This means the DTO for create and read are now different
This means the base URL for create and read are now different (the base class assumed they were the same)
TODO - add hearing and punishment mappings to DTO
> SDIT 927 mapping record change DTO and URL

- helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml
- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt
While DPS is understanding their mapping issues they will throw a 4xx error. For these, when we are in the special "reporting" mode, we ignore the error, but gather some stats
> SDIT-928 tactical short term change to "ignore" 4xx errors

- openapi-specs/activities-api-docs.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/ActivitiesApiMockServer.kt
There were some fairly substantial changes to the appointments part of the activities API. This was to bring the taxonomy in line with the UI. In brief:
- Appointment Occurrence -> Appointment - the event at a specific date, time and location
- Appointment -> Appointment Series - a collection of Appointments on a regular cadence defined by a schedule
- Bulk Appointment -> Appointment Set - a collection of Appointments taking place on the same date and in the same location but at optionally different times
- Appointment Occurrence Allocation -> Appointment Attendee - a prisoner attending a specific appointment
Additionally some key properties have been renamed to match the UI labels or an activities convention:
- appointmentDescription -> customName
- comments -> extraInformation
- created …
> SAA-1162: Update activities-api-docs.json and use returned AppointmentInstance

- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/nonassociations/NonAssociationsMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/nonassociations/NonAssociationsSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationIntTest.kt
Add the performMigration() solution rather than just waiting untilAsserted inline in each test
> SDIT-1112 Fix flaky non-assoc tests

- helm_deploy/hmpps-prisoner-from-nomis-migration/Chart.yaml
- helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
> Migrating project to use groups in allowlist

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/WebClientHelpers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/AdjudicationsApiMockServer.kt
This wiring in the mapping creation service.
The scenario is as follows
- Try migrate adjudication
- DPS POST fails with timeout but does successfully migrate item
- No mapping is created due to POST timeout
- Retry message
- DPS POST now fails with a 406 (meaning adjudication already migrated)
- Ignore 406 but instead programmatically create mapping ourselves
> SDIT-1247 Try to create mapping with DPS returns a 406

- openapi-specs/adjudications-api-docs.json
- openapi-specs/nomis-sync-api-docs.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationMappingCreatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationTransformationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
DPS requires the `nomisSplitRecord` flag to indicate that the original NOMIS record had multiple charges which are now multiple Adjudications in DPS.
DPS will apparently drive additional info copy in their UI from this flag
> SDIT-1429 Populate Adjudication nomisSplitRecord from NOMIS hasMultipleCharges

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationMessageListener.kt
Connection pool size is 10 and default thread listener is 10 - when any other endpoint is called that requires a connection (e.g. healthcheck), it can use more connections than in the pool - hence 500 errors. This is a particular issue during early stages of Adjudication migration due to the get IDs endpoint being so CPU intensive.
> SDIT-1436 Reduce Adjudication listener threads to 8

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationTransformationTest.kt
When NOMIS merges prisoners it appears to set the punishment created by username as SYS. Since this is not a real user fall-back to hearing result user (which are not changed by merge). This fixes issue in DPS where it attempts to retrieve staff details for the username 'SYS'
> SDIT-1437 Fix merged created by username for punishment

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsMigrationMessageListener.kt
Connection pool size is 10 and default thread listener is 10 - when any other endpoint is called that requires a connection (e.g. healthcheck), it can use more connections than in the pool - hence 500 errors. This is a particular issue during early stages of incidents migration due to the get IDs endpoint being so CPU intensive.
This is the same change made to the AdjudicationsMigrationMessageListener.
> SDIT-1375 Reduce Incidents Listener threads to 8

- helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsPrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/TestBase.kt
Introduced handling for "ALERT-UPDATED" and "ALERT-INSERTED" events in the HMPPS Prisoner from NOMIS migration service. Modified YAML values to add features for these events and updated queues to manage alerts. Added new classes for service and test of alert synchronization and updated existing classes to support these changes.
> SDIT-1503 Add prison alert event handling for alerts

- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsNomisApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingPrisonOffenderEventListener.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsNomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsNomisApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
This update includes essential changes in the SentencingAdjustmentsSynchronisationService to handle prisoner merge events so it can synchronize sentence and key date adjustments. Moreover, these modifications follow the introduction of SentencingAdjustmentsNomisApiService to interact with the NOMIS API. The update also involves new test cases ensuring that the prisoner merge handling works correctly.
> SDIT-1591 Add prisoner merge event handling for Sentencing Adjustment

- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsPrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
Will delete alert in DPS if mapping still exists and try to delete the mapping
> SDIT-1606 Handle ALERT-DELETED prisoner event

- openapi-specs/nomis-sync-api-docs.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMessageListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMigrationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiServiceTest.kt
- src/test/resources/application-test.yml
This is feature switched via alerts.migration.type with test by default using old method and deployed service using skeleton of new.
This allows us to hedge our bets depending on what we find when only migrating some alerts from previous bookings. If we discover this is not acceptable we can easily revert back to old method.
This version only track telemetry event showing how many previous alerts will be made active by this approach.
> SDIT-1658 First pass at skeletion for migrating alerts by prisoner

- openapi-specs/nomis-mapping-service-api-docs.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMappingApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt
Since this does not follow usual pattern of teh count of mappings matches the count on the number of entities migrated, we override the count function to count the number of prisoners migrated else the number recorded ends up zero
> SDIT-1614 Migrate Alerts - record number of prisoners migrated

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMessageListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMappingApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
Mapping now has offenderNo on table so that mappings can be deleted by prisoner. This requires a new POST endpoint and also added offenderNo to the single version of the POST
> SDIT-1614 Use new prisoner centric mapping POST endpoint

- openapi-specs/nomis-mapping-service-api-docs.json
- openapi-specs/nomis-sync-api-docs.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
These are identified with the NOMIS standard copy table audit text. When this happens the alert mapping needs updating to point to the new booking. There are no changes required in DPS
> SDIT-1546 Handle alerts created due to a new booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
For a merge duplicates can happen since they will not be rejected by DPS, therefore a network issue can result in this scenario
> SDIT-1568 - Handle duplicates for batch alerts

- .circleci/config.yml
4 parallel executors roughly halved the time to test. Going up to 8 executors only shaved another 1-2 minutes off the total testing time. It seems that a lot of the time is taken up by Gradle rather than just tests running, hence the diminishing returns.
> SDIT-1703 Split Circle tests into parallel executors

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
It is possible to process an UPSERT event from NOMIS after an adjustment is deleted - this can happen if events are delayed. In this scenario just ignore the update rather than sending to DLQ
> SDIT-1835 Ignore updates to adjustments deleted

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDataRepairResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/data/NomisPrisonerMergeEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/listeners/MigrationMessageType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDataRepairResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/Messages.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
SDIT-1859 Resynchronising alerts on receive to old bookings  
When a prisoner is received on a old booking the alerts in DPS need resetting to match alerts in NOMIS therefore we need to 
* Get all current alerts as if this is a migration
* Replace alerts in DPS
* Replace mappings
TODO
* Call new DPS resynchronisation endpoint when available
* Narrow down scenario for old bookings that requires a search change
> SDIT-1859 Resynchronising alerts on receive to old bookings  

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
Since there are edge cases where we can't work out what the previous booking is - this change uses the resync endpoint to simply replace all alerts in DPS on a new booking
> SDIT-1859 Resynchronising alerts to DPS API in new admission

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesPrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPPrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsPrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/listeners/EventFeatureSwitch.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/prisonperson/PrisonPersonEventListener.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/listeners/EventFeatureSwitchTest.kt
This allows to switch off generic events e.g. prison-offender-events.prisoner.merged for a domain.
FEATURE_EVENT_PRISON-OFFENDER-EVENTS_PRISONER_MERGED would become FEATURE_EVENT_ALERTS_PRISON-OFFENDER-EVENTS_PRISONER_MERGED to turn-off just for alerts. No domains require this so far but added the domain parameter for ones in progress
> SDIT-1858 Added the ability for domain switch for generic events.

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/data/NomisPrisonerMergeEvent.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/Messages.kt
When a booking is moved from Prisoner A to Prisoner B, Prisoner B would have already resynchronised, but the source prisoner (Prisoner A) need to be resynchronised as well
> SDIT-1886 Resynchronise alerts after a booking has moved.

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationsMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/MigrationService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationsMigrationServiceTest.kt
- src/test/resources/application-test.yml
Previously migrations would incorrectly wait for the same amount time it would wait at the beginning of a migration for the initial slow "get ids" query compared to  the end of the migration.
This is now a separate config.
For contacts,allocations,activities this is set to 10 seconds all others are whatever the value is now to not break anything
> SDIT-2089 Correct slow complete migration logic

- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
Slow down the migration so that the cancel has time to finish before the migration is complete
> SDIT-2089 Fix flaky cancel tests

- openapi-specs/nomis-sync-api-docs.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesByPrisonerMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesMappingApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesByPrisonerMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesNomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesNomisApiServiceTest.kt
New logic in the case notes merge which avoids migrating duplicate case notes created by merges, but including mappings for them pointing to the same DPS id as the original case notes
> SDIT-2248 Revised case notes merge strategy

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
A bit more complicated than other sync events since:
* NOMIS has single event for person phones and phones associated with an address
* DPS has different endpoints for the address and the global phone numbers
* For an address related phone we therefore have to look up the DPS address Id as well
> SDIT-2270 Handle PHONES_PERSON-INSERTED

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt
It can be null during a cascading delete where the contact has already been deleted
> SDIT-2290 offenderIdDisplay can be null

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsNomisApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsDataRepairResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsNomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsNomisApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/SentencingApiMockServer.kt
Initial changes to support a new migration to update a single "currentTerm" flag for all DPS adjustments using a new PATCH endpoint.
* Integration to call the GET adjustments IDs endpoint from NOMIS
* Integration to call the PATCH DPS endpoint to update the currentTerm flag
Also refactored NOMIS API integration so uses own adjustment class and mocks which is standard these days
> SDIT-2385 Integration to adjustment get ids and current term patch

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationIntTest.kt
NOMIS has a single event and table for email and web but DPS and Mapping have separate endpoints; so a little bit more complex when mapping
> SDIT-2435 Handle INTERNET_ADDRESSES_CORPORATE-INSERTED

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingDpsApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMappingApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingDpsApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingNomisApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
Half working version based on existing DPS endpoints that shoud at least:
* Show new cases being created
* Show court cases and sentences being deactivated
However, without new endpoint cases from the removed prisoner number will not see the cases moved to the retained prisoner.
Done
* Call existing (unsuitable) DPS endpoint
TODO
* call new DPS endpoint to sync
* call mapping for new mappings
> SDIT-2694 Basic plumbing for merge court support

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiServiceTest.kt
Repair endpoint for certain POM contacts can take over 30 seconds - this ensures we wait a longer time given this is only called manually
> SDIT-2723 Allow large DPS timeout when running manual repair

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDataRepairResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDataRepairResourceIntTest.kt
Can be used as an alternative to repair person; but just resynchronizes the relationships and leave the core person untouched
> SDIT-2753 Add repair contacts endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationIntTest.kt
Handle by doing nothing and just emitting telemetry that we can double check since it should mean we have double POSTed due to network error
> SDIT-2761 Handle 409 for DPS create contact

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationIntTest.kt
When a contact is being removed and added at the same time, DPS will correctly return 409 if the contact delete hasn't be processed yet. So just keep retrying until there is manual intervention.
> SDIT-2761 Retry on duplicate contacts

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/GeneralMappingService.kt
So that migration mapping uses the correct count
> SDIT-2889 User PrisonerRestriction mapping for contact person domain

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
Refactor prep work before update service sends these new fields for cases updated with new booking id and the adjustments that have been created.
TODO - assert logic works then send the new fields
> SDIT-2982 Amend resync case booking event
