ministryofjustice/hmpps-prisoner-from-nomis-migration

build.gradle.kts, helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml, src/main/resources/application-localstack.yml, src/main/resources/application.yml
Only health check is implemented so far
=> SDI-33 SQS Integration

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/listeners/MigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Messages.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/visits/VisitsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt, src/test/resources/application-test.yml
After calculating how many pages there are of visits, each unique visit id is retrieved and a message sent to migrate that visit
=> SDI-33 Send message for each visit

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/visits/VisitsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitMappingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/VisitMappingApiMockServer.kt
I have outstanding question which is what do we do if we find no room
=> SDI-33 Retrieve room mapping

.circleci/config.yml, Dockerfile, README.md, build.gradle.kts, docker-compose-local.yaml, docker-compose.yml, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/config/PostgresContainer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt, src/test/resources/application-test.yml
Adds integration to Postgres but yet to actually use it for anything
1) Should work in Cloud Platform
2) health check works locally with just postgres and localstack running
3) health check works locally when everything is working in localstack
=> SDI-104 Add integration with postgres database (no read/write yet)

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/config/OpenApiConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/persistence/repository/MigrationHistory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/resources/MigrationHistoryResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitMigrationResource.kt
- Adds roles to swagger documentation
- Minor json ignore on `new` property since this object is returned back to endpoint without a DTO (which would be identical)
=> SDI-104 Added roles to swagger

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/listeners/MigrationMessageListener.kt
The hope is we can easily link a message on DLQ with an exception is Application Insights
=> SDI-119 Log message id with exception

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/MigrationQueueService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationService.kt, src/main/resources/application.yml, src/test/resources/application-test.yml
A bit experimental; but attempt to purge queue every second for half a minute to remove messages being added by other threads
=> SDI 227 cancel purge delay

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentiveMigrationProperties.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentiveMigrationPropertiesTest.kt
TODO - get current migration count and last migration
=> SDI 355 Info incentives properties

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/incentives/IncentivesMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
Add call to retrieve IEP from NOMIS 
TODO - migrate it to incentives!
=> SDI-355 incentives migration

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/MockIncentivesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/SpringAPIServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/incentives/IncentivesMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/incentives/IncentivesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/IncentivesApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
Now calls the Incentives API
TODO: retrieved offender number and module name from nomis API
=> SDI-355 Call incentive migrate endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/MockIncentivesResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/IncentivesApiMockServer.kt
Some cleanup of unused methods left by various merges
=> SDI-377 Add mock logging and switched to PATCH for incentive update

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/listeners/PrisonOffenderEventListener.kt
Does nothing other then log whether we would delete the incentive
=> SDI-424 Skeleton for deleting incentives

helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentiveMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incentives/IncentivesSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/Messages.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/incentives/IncentivesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/incentives/PrisonerFromNomisIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/IncentivesApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
=> Sdi 424 delete incentive

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/MockSentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMappingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/SentencingApiMockServer.kt
TODO more exception handling, particularly around mapping create failures
=> SDI-554 Happy create / update sentence adjustment path

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
This is a cut and paste of Sentence adjustments with minor changes like events names, telemetry names.
Next stage will be to reduce duplication
=> SDI-550 CRUD for key date adjustments

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMappingService.kt
This reverts commit ae432865462aecee07be092dd307ee06164ef2f2.
=> Revert "sdi-637 handling duplicate adjustment during migration (#241)"

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
When NOMIS creates key date adjustments it also creates sentence adjustments, these don't need to synchronised with Digital Warrant
=> SDI-550 Ignore sentence adjustments related to key date adjustments

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsSynchronisationIntTest.kt
=> SDIT-699 VSIP rejects cancellations from NOMIS when historical

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMappingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/ActivitiesApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
=> Sdit 752 appointments migration in from nomis 

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationPropertiesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsServiceTest.kt
=> SDIT-752 Appointments migration in from-nomis

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMappingService.kt
=> SDIT-800 Link up the activities api migrate appointments endpoint

build.gradle.kts
upgrade to test the sqs lib change
=> SDIT-865 Improve Get DLQ API in SQS lib

README.md, build.gradle.kts, openapi-specs/adjudications-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/AdjudicationsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
* Add additional test to give clarity on how we migrate and specific adjudication 
* Import adjudication DPS classes for next stage
=> SDIT-941 Improve test and import DPS adjudication classes

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/MockAdjudicationsResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/SpringAPIServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/AdjudicationsApiMockServer.kt
* Uses the real DPS DTOs for create adjudications and response
* No real transformation done yet that is all TODO
=> SDIT-928 Basic DPS structure but with no sensible mapping between them yet

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationTransformationTest.kt
Prisoners can either be
- suspects (so in this scenario other suspects involved in the incident)
- victims
- witnesses
Staff can either be
- victim
- witness
Reporting Officer (oddly along side the main reporting officer)
Control and restraint (so I guess used in the incident)
Other
So give we have a single “witness” list with types of OFFICER, STAFF, OTHER_PERSON, VICTIM, PRISONER I think the best I can do it is as follows:
- All staff witnesses - become STAFF
- All prisoners witnesses - become OTHER_PERSON (obviously there are very few of these)
- All victims (staff or prisoners) - become VICTIM
- All other prisoners (e.g other suspects) become PRISONER
- All other staff (the last 3 on that list) becomes OTHER_PERSON
=> SDIT-928 Add other parties to DPS DTO

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationTransformationTest.kt
TODO
- Mapping when type is NULL
- Results
=> SDIT-928 Basic hearing mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationTransformationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationIntTest.kt
=> SDIT-928 Basic outcomes and results

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationTransformationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationIntTest.kt, src/test/resources/application-test.yml
DPS always records in days but NOMIS sometimes (rarely) uses months; so 2 months wage deduction. The best we can do is convert this back into days based on when punishment started (so February is a good month to be punished)
=> SDIT-928 Calculate award days when supplied in months

openapi-specs/adjudications-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationTransformationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsServiceTest.kt
Temp changes required to run a migration
TODO
* Change NOMIS API to get data
* Wire in the correct data
=> SDIT-928 Temp fix for new fields in adjudication migration

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt
Currently DPS does not return a mapping for some punishments it can not process, this cause the entire migration record to fail..
While this is WIP in DPS this change ignores the missing mapping and just warnings.
Code hack can be revered once DPS is fixed but right now it gets in the way of analysis
=> SDIT-1085 Temporary hack to prevent null sanction seq from causing error

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/nonassociations/NonAssociationsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
=> SDIT-1112 Fix flaky non-assoc tests

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationMappingCreator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationMappingCreatorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/AdjudicationsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
* TODO Punishments
* Wire in service when there is a fix required
=> SDIT-1247 Match hearings

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationMappingCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationMappingCreatorTest.kt
TODO
- Wire in service so it is called on certain failures
=> SDIT-1247 Match punishments

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
And 4xx error returned by DPS will now be treated as an error
=> SDIT-1127 Switch report mode off for adjudications

README.md, build.gradle.kts, openapi-specs/sentencing-adjustments-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/SentencingApiMockServer.kt
Switched to OpenAPI generated Adjustment API classes
=> SDIT-1428 Populate bookingReleased flag to show parent booking is inactive

README.md, build.gradle.kts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, openapi-specs/alerts-api-docs.json, openapi-specs/nomis-mapping-service-api-docs.json, openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/WebClientHelpers.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/health/HealthCheckTest.kt, src/test/resources/application-test.yml
Two new concepts introduced:
1) Alert specific versions of the nomis and mapping apis 
2) Alert specific versions of wiremock helper classes
This helps to keep alert specific code together
=> SDIT-1505 Integration with alerts NOMIS and Mapping APIs

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiServiceTest.kt
* Correct the URL 
*  distinguish between 200 and 201 responses
=> SDIT-1505 Integration with alerts DPS APIs

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/Transformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/Telemetry.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
* Assumes DPS API uses NOMIS model - we know this will change
* TODO - need prisoner number
* TODO - handle mapping errors
* TODO - handle mapping already exists
=> SDIT-1505 Handle simple create alert scenario

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/Telemetry.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Helpers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt, src/test/resources/application-test.yml
* TODO - need prisoner number
* TODO - handle mapping already exists
=> SDIT-1505 Handle scenario where mapping create fails

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/Transformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
* TODO - handle mapping already exists
=> SDIT-1505 Add prisoner number to transform and telemetry

openapi-specs/alerts-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/Transformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt, src/test/resources/application-test.yml
* Now a separate DPS POST/PUT endpoint
* Created/Modify username passed via header
* Also switch-off throwing exceptions when attempting to update an Alert that has not been migrated yet
=> SDIT-1517 Move to latest DPS model for Alerts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt
This was present for sentence adjustments but entirely missing for key-date adjustments
=> SDIT-1567 Added handling of duplicate key-date adjustments

README.md
Also removed redundant Adjudication stuff and correct structure headings
=> SDIT-1567 Added Sentencing Adjustments runbook

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsSynchronisationIntTest.kt
=> SDIT-1522 Location From Nomis sync

openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationServiceTest.kt
Add migration of location history
=> SDIT-1522 Location From Nomis sync - history

helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMigrationFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/Transformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/GeneralMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Helpers.kt, src/main/resources/application-localstack.yml, src/test/resources/application-test.yml
Minimal code to check the new Alert migration queues are working
=> SDIT-1614 Alert migration scaffolding

openapi-specs/alerts-api-docs.json, openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/WebClientHelpers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/PageContentHelpers.kt
When DPS sees a duplicate from NOMIS it will return a 409 - so the intention is to log and ignore these
=> SDIT-1614 Alert migration plumbing

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationServiceTest.kt
Always set deactivation reason if not active
=> SDIT-1620 From-nomis migration and sync of location deactivation data

openapi-specs/locations-api-docs.json, openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/LocationsApiMockServer.kt
Fix problem with duplicate history items by just updating history in the main location migeration dto
=> SDIT-1619 Locations reconciliation - improve migration

openapi-specs/alerts-api-docs.json, openapi-specs/nomis-mapping-service-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/Transformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/MigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt
The DPS API accepts a list of alerts for the prisoner and that list is transformed into mapping that is POSTed in a single batch.
Since only one duplicate mapping can be duplicate the duplicate mapping handling differs for the usual pattern. This still requires a integration test
=> SDIT-1614 Alert Migrate calls DPS and Mapping APIs

.circleci/config.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/GeneralMappingService.kt
This will give a count of prisoners migrated rather than alerts based on feature switch
=> SDIT-1614 Use new prisoner centric mapping GET endpoint

build.gradle.kts
Bump sqs library version to test new beta
=> SDIT-864 Improve RetryDLQ in SQS lib

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsSynchronisationIntTest.kt
deletion of a location attribute or usage should just result in an overall update
=> SDIT-1696 Deletion locations sync events handled wrongly

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/data/NomisPrisonerMergeEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingPrisonOffenderEventListener.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/Messages.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
Sentencing adjustments also process merges so small refactor to share code better
=> SDIT-1568 Scaffolding to handle prisoner merges for alerts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/data/NomisPrisonerMergeEvent.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
TODO need new DPS service for next part
=> SDIT-1568 Workout what new alerts after merge

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
Has virtually no impact other that confusion, but mapping should indicate it was created by NOMIS not DPS
=> SDIT-1568 - Fix incorrect mapping type

openapi-specs/locations-api-docs.json, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/LocationsApiMockServer.kt
The locations api contract has changed slightly
=> Update locations deactivation enum

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
…
Alerts created on previous bookings are considered relevant if they do not exist on the latest booking
=> SDIT-1730 Ignore alerts created on previous bookings unless they are "relevant"

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMessageListener.kt
Reduce this problem of connection timeouts on 10 sized connection pool
=> SDIT-1753 Reduce migration threads to 8

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsRepairResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsRepairResourceIntTest.kt
Add a from-nomis endpoint which resynchronises from Nomis to DPS
=> SDIT-1793 Locations Create a repair endpoint

.circleci/config.yml
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-prisoner-from-nomis-migration/2400/workflows/779aca58-e36b-4ecd-9408-bc0670f31cbb/jobs/7323/parallel-runs/10?filterBy=ALL
=> SDIT-1703 Create a parallel executor per package

helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/MockCSIPResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Helpers.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/main/resources/application-localstack.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMappingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/SpringAPIServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/health/HealthCheckTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/MappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
A lot of files but many are just restructure changes.
=> SDIT-1487 Add CSIP sync queues and INSERT sync

openapi-specs/alerts-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt
Now also tell DPS the list alerts that were retained. Also delete the orphaned mappings straight away rather than waiting for the associated domain event
=> SDIT-1836 Improve handling of merges for alerts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helper/Messages.kt
* Narrow down scenario for old bookings
=> SDIT-1859 Resynchronising alerts on receive to old bookings

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/MockCaseNotesResource.kt
=> SDIT-1852 Casenotes migration

openapi-specs/incidents-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsServiceTest.kt
Depends on [hmpps-incident-reporting-api#139](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/139)
=> IR-385: Update incident reporting service data model and URLs

openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt
When the "from" prisoner is inactive resynchronise alerts. When they are active the alerts would have resynchronised anyway due to the new active booking.
=> SDIT-1929 Booking move now updates both parties

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/config/WebClientConfiguration.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationPerformanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/HmppsAuthMockServer.kt
Also added test to expose issue and demonstrate fix. Test can be deleted once fix is incorporated into kotlin template library
=> SDIT-1931 Set token retrieval timeout

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesSynchronisationIntTest.kt
=> SDIT-1898 Switch mock casenotes-api to real one

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationIntTest.kt
further work on charges to come as mappings are shared across appearances
=> sdit-2059 adding in appearances and charges to court case migration

helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/GeneralMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Helpers.kt, src/main/resources/application-localstack.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt
No functionality yet, so nothing to test, But should assert queues are set up correctly else deployment will fail.
=> SDIT-2089 Initial minimal framework code for contacts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonNomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonNomisApiServiceTest.kt, src/test/resources/application-test.yml
Test for history endpoints and a zero sized migration
=> SDIT-2089 Initial resource for contact migration

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/prisonperson/PrisonPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/prisonperson/PrisonPersonMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/MigrationVisitsMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsPrisonOffenderEventListener.kt
Reverts ministryofjustice/hmpps-prisoner-from-nomis-migration#859
Test out theory that the extra span was causing the parent RECEIVE span to be closed as well
=> Revert "SDIT-2060: 🔥 Remove calls to WithSpan as now using distributed tracing from sqs library instead"

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/adjudications/AdjudicationsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsByPrisonerMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/prisonperson/PrisonPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/prisonperson/PrisonPersonMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingPrisonOffenderEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/MigrationVisitsMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsPrisonOffenderEventListener.kt
Reverts ministryofjustice/hmpps-prisoner-from-nomis-migration#868
=> Revert "Revert "SDIT-2060: 🔥 Remove calls to WithSpan as now using distributed tracing from sqs library instead""

openapi-specs/nomis-sync-api-docs.json, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonNomisApiMockServer.kt
=> SDIT-2089 NOMS API DTO regeneration

openapi-specs/contact-person-api-docs.json, openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonNomisApiMockServer.kt
Use very old version of DPS migrate endpoint and change tests to use it.
TODO - new version of endpoint to be released very soon
=> SDIT-2090 Pre-work for calling DPS migrate endpoint

openapi-specs/contact-person-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/MigrationHistoryService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/MigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/ActivitiesMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/activities/AllocationsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/appointments/AppointmentsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/csip/CSIPMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/locations/LocationsMigrationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/visits/VisitsMigrationServiceTest.kt
Also fix cancelling a migration can result in status being set to COMPLETED
=> SDIT-2090 use latest dps contact endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
Added meaningless active flag for PERSON to see if the DPS endpoint actually works.
=> SDIT-2090 Basic handling of PERSON-INSERTED

openapi-specs/contact-person-api-docs.json, openapi-specs/nomis-mapping-service-api-docs.json, openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
Create a prisoner contact in DPS
=> SDIT-2266 handle OFFENDER_CONTACT-INSERTED

openapi-specs/contact-person-api-docs.json, openapi-specs/nomis-mapping-service-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiServiceTest.kt
TODO - actually processing of message
=> SDIT-2269 Integrate with DPS and Mapping address endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesByPrisonerMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesSynchronisationIntTest.kt
Taking previous merges into account
=> SDIT-2250 Revised case notes from-nomis sync logic

openapi-specs/contact-person-api-docs.json, openapi-specs/nomis-mapping-service-api-docs.json, openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
* Integration with the identity/identifiers endpoints
=> SDIT-2270 Handle PERSON_IDENTIFIERS-INSERTED

openapi-specs/nomis-mapping-service-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiServiceTest.kt
=> SDIT-2275 Handle PERSON_RESTRICTION-UPSERTED

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
=> SDIT-2275 Handle VISITOR_RESTRICTION-UPSERTED

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
Only 2 events are upserts so a bit more messy which involves a small amount of renaming and better telemetry
=> SDIT-2282 Update version of VISITOR_RESTRICTION-UPSERTED

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
This is the 2nd event that uses an upserts so a bit more messy which involves a small amount of renaming and better telemetry
=> SDIT-2275 Update version of PERSON_RESTRICTION-UPSERTED

openapi-specs/contact-person-api-docs.json, openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
Also refactor for telemetry success/error handling
=> SDIT-2280 PERSON_IDENTIFIERS-UPDATED

openapi-specs/sentencing-adjustments-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/wiremock/NomisApiMockServer.kt
=> SDIT-2357 Add current term flag for adjustments

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/Telemetry.kt
=> SDIT-2280 Move telemetry function

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonSynchronisationIntTest.kt
and PERSON_IDENTIFIERS-DELETED
=> SDIT-2285 ADDRESSES_PERSON-DELETED, INTERNET_ADDRESSES_PERSON-DELETED

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesByPrisonerMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesByPrisonerMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesMergeIntTest.kt
Revised migration algorithm using groupBy
=> SDIT-2366-Case-notes-migration-confused-by-identical-case-notes

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationIntTest.kt
DPS wants the enteredBy username for either the modified or created username since this is more likely to correspond to the real user that created or modified the restriction (for instance it survives a merge)
This would only affect a tiny percentage of contact restrictions but is needed since DPS has dropped the notion of the separate "enteredBy" field and rely on the audit fields
=> SDIT-2043 Used "Entered By" username for restrictions

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesByPrisonerMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/casenotes/CaseNotesSynchronisationService.kt
Ensure amendments are considered in identical check
=> SDIT-2366 Case notes migration confused by identical case notes

helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingAdjustmentsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/GeneralMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Helpers.kt, src/main/resources/application-localstack.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingMigrationIntTest.kt
Unlike a normal migration this will patch existing adjustments by reading all adjustments, and for each adjustment find the associated mapping and call the PATCH DPS endpoint
=> SDIT-2385 Patch migration for sentence adjustments

openapi-specs/nomis-mapping-service-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMappingApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMappingApiServiceTest.kt
=> SDIT-2410 Corporate Migration queues and service

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMigrationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/contactperson/ContactPersonMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMigrationIntTest.kt
Just migrates the organisation name
TODO - more details and child elements
=> SDIT-2410 Corporate Migration - basic migration

openapi-specs/nomis-mapping-service-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMappingApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/corporate/CorporateMappingApiServiceTest.kt
And rename for corporate/corporate mapping url to corporate/organisation
=> SDIT-2477 POST corporate organisation mapping integration

helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMigrationFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMigrationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/GeneralMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Helpers.kt, src/main/resources/application-localstack.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsNomisApiServiceTest.kt, src/test/resources/application-test.yml
Class name and config changes
TODO: telemetry name changes
=> SDIT-2552 Rename Corporate classes to Organisations

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationIntTest.kt
and refactor Mapping creation to reduce shared code
=> SDIT-2442 Handle ADDRESSES_CORPORATE-INSERTED

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt
Use Kotlin 2.1 guard for better readability
=> SDIT-2430 Handle PHONES_CORPORATE-INSERTED Event

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationIntTest.kt
Double complication:
NOMIS has a single event and table for email and web but DPS and Mapping have separate endpoints; so a little bit more complex when mapping
Also in NOMIS a web address can be converted to email address and vice versa; in these scenarios we need to perform a DELETE in DPS and mapping service followed by creates
=> SDIT-2435 Handle INTERNET_ADDRESSES_CORPORATE-UPDATED

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationIntTest.kt
NOMIS has a single event and table for email and web but DPS and Mapping have separate endpoints; so a little bit more complex when mapping
=> SDIT-2435 Handle INTERNET_ADDRESSES_CORPORATE-DELETED

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationIntTest.kt
Unsure if DPS will use these but made the core organisation sync consistent with all other entities
=> SDIT-2443 Added core organisation audit fields

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationIntTest.kt
Since there can either be a web or email mapping we need to specifically deal when neither mapping is found and throw exception
=> SDIT-2442 INTERNET_ADDRESSES_CORPORATE-UPDATED no mapping scenario

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/organisations/OrganisationsSynchronisationService.kt
Was previously using null to indicate if a web or email mapping was found. Now use sealed class and refactor large function into 4 smaller ones.
=> SDIT-2442 INTERNET_ADDRESSES_CORPORATE-UPDATED refactor

openapi-specs/nomis-mapping-service-api-docs.json, openapi-specs/personal-relationships-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/profiledetails/ContactPersonProfileDetailsDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/profiledetails/ContactPersonProfileDetailsSyncIntTest.kt
Also integration for update/delete employments
=> SDIT-2273 Handle PERSON_EMPLOYMENTS-INSERTED

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiServiceTest.kt
=> SDIT-2374 Contact prisoner merge integration

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationIntTest.kt
* Reset contacts in DPS to match NOMIS after the latest booking has changed
=> SDIT-2377 Reset contacts after a prisoner receive

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/alerts/AlertsSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/helpers/SynchronisationHelpers.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationIntTest.kt
* Reset contacts in DPS to match NOMIS after the latest booking has moved
* When the latest booking is not active also reset the other prisoner
=> SDIT-2375 Process move bookings for contacts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
Done
* Call nomis api to get cases changed
TODO
* call DPS endpoint to sync
* call mapping for new mappings
=> SDIT-2694 Basic plumbing for merge court support

openapi-specs/court-sentencing-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/Transformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingTransformerTest.kt
A linked court cases is where multiple cases are heard at the same time so the charges from one are copied to another. The original cases is deactivated in NOMIS
=> SDIT-2713 Migrate linked court cases

openapi-specs/court-sentencing-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/Transformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/SentencingSynchronisationIntTest.kt
DPS changes to accept a list of charge for a sentence
=> SDIT-2714 Multiple charge on single sentence

build.gradle.kts, openapi-specs/incidents-api-docs.json, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsApiMockServer.kt
=> SDIT-1986 Pick up latest incidents api spec (descriptionAddendums added)

openapi-specs/nomis-prisoner-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationIntTest.kt
getPersons is very slow for person records with 1000s of contacts
=> SDIT-2723 User getContacts slim endpoint rather than getPerson

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDataRepairResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDataRepairResourceIntTest.kt
Repair can take several minutes for some contacts
=> SDIT-2723 Add async version of contact repair

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
=> SDIT-2715 Basic integration with case and charge linking

build.gradle.kts, openapi-specs/incidents-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsDataRepairResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsNomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentDataRepairResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/incidents/IncidentsMigrationServiceTest.kt
=> SDIT-2745 Add ability to create an incident as part of repair endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationIntTest.kt
DPS does not support this tiny number of prisoner to prisoner contacts (7 in last  year)
=> SDIT-2769 Ignore contacts CRUD events for prisoner to prisoner contacts

openapi-specs/court-sentencing-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/Transformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationIntTest.kt
Also clarify issues with the existing approach
=> SDIT-2772 Supply linked date for combined cases

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
Get active recalls
TODO get mappings and update DPS
=> SDIT-2768 Basic OFFENDER_FIXED_TERM_RECALLS-* integration

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
DPS is updated with the updated sentences related to bookings whose date has changed
=> SDIT-2768 OFFENDER_FIXED_TERM_RECALLS-UPDATED integration

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/Transformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingTransformerTest.kt
And removed DPS fields due to be deleted
=> SDIT-2909 Fixed case linking logic

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonMigrationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionMigrationFilter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/profiledetails/ContactPersonProfileDetailsSyncIntTest.kt
TODO:
* Get prisoner number back from NOMIS API
* Fix tests that rely of prisoner number
=> SDIT-2889 Convert person migration to prisoner restrictions

openapi-specs/personal-relationships-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionMappingApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionMigrationIntTest.kt
* Create/Update/Delete DPS APIs
* Delete/Lookup Mapping APIs
=> SDIT-2900 Prisoner restrictions integration

helm_deploy/hmpps-prisoner-from-nomis-migration/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionsDomainEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/Helpers.kt, src/main/resources/application-localstack.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/personalrelationships/PrisonerRestrictionSynchronisationIntTest.kt
Restrictions now hooked up to booking related changes
TODO - implement actual changes
=> SDIT-2885 Listeners for booking related domain events

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/SynchronisationQueueService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
This will be called by the sync to NOMIS service to sync back to DPS so that it can store the bookingId
=> SDIT-2977 Resync court case

openapi-specs/court-sentencing-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
bookingId was nullable in DPS so this was missed
=> Sdit 2977 court case booking id fix

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/integration/SqsIntegrationTestBase.kt
The issue was errorVisibilityTimeout was 1 second running tests, so occasionally we hit retries sometimes we didn't
=> SDIT-2977 Flaky test fix

openapi-specs/nomis-mapping-service-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationMessageListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/service/SynchronisationQueueService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
Rename of mapping class CourtCaseBatchMappingDto
TODO - implementation of case resync
=> SDIT-2982 Add resync case booking event

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/sentencing/SentencingSynchronisationIntTest.kt
Test for court case and sentence updated with booking id
Test for sentence adjustments created via booking clone
=> SDIT-2982 Amend resync case booking event

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/Transformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationIntTest.kt
Also call getCourtCases NOMIS API endpoint.
The DPS endpoint is currently identical to the migration endpoint other than the type names so a lot of copy and paste from the migration code.
=> SDIT-2983 Call DPS booking create endpoint for clone

openapi-specs/nomis-mapping-service-api-docs.json, openapi-specs/nomis-prisoner-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/movements/ExternalMovementsNomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/movements/ExternalMovementsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/movements/ExternalMovementsNomisApiServiceTest.kt
=> SDIT-2850 Add NOMIS temporary absence API clients

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingMigrationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingRepairResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingRepairService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingRepairResourceIntTest.kt
Essentially a wrapper for migration without the full migration excesses
=> SDIT-3078 Repair prisoner court cases endpoint
